# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: build

  build:
    desc: Compiles all Elm files to our assets/elm.js
    cmds:
      - elm make --output=assets/elm.js --optimize src/Main.elm
    sources:
      - src/**/*.elm
    generates:
      - assets/elm.js

  dev-server:
    desc: Starts a small Python server for development purposes
    deps:
      - build
    cmds:
      - task: build
      - python -m http.server --bind 127.0.0.1 8000
