# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: run

  build:
    desc: Build the binary but don't run it
    cmds:
      - roc build
    sources:
      - main.roc
      - Solution/*.roc
      - Solution/*.input
    generates:
      - main

  run:
    desc: Build the binary and run it
    cmds:
      - task: format
      - task: build
      - ./main {{ .CLI_ARGS }}

  format:
    desc: Format roc files
    cmds:
      - roc format main.roc Solution/*.roc
    sources:
      - main.roc
      - Solution/*.roc

  prepare-next-day:
    desc: Creates files for the next day (just a small helper which takes only some steps ...)
    cmds:
      - cp Solution/DayX.roc.tpl Solution/Day{{ .CLI_ARGS }}.roc
      - touch Solution/Day{{ .CLI_ARGS }}.input
